accounts/urls.py
from django.urls import path, include

from accounts.views import ProfileView

app_name = 'accounts'


urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('profile/<int:pk>', ProfileView.as_view(), name='user_profile')
]

api/urls.py
from django.urls import path
from . import views

app_name = 'api'

urlpatterns = [
    path('photo/favorite/<int:pk>/', views.FavoritePhotoApiView.as_view(), name='fav_photo'),
    path('photo/unfavorite/<int:pk>/', views.UnFavoritePhotoApiView.as_view(), name='unfav_photo'),
    path('album/favorite/<int:pk>/', views.FavoriteAlbumView.as_view(), name='fav_photo'),
    path('album/unfavorite/<int:pk>/', views.UnFavoriteAlbumApiView.as_view(), name='unfav_photo'),
]

exam9/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('auth/', include('accounts.urls')),
    path('api/', include('api.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webapp/urls.py
from django.urls import path
from . import views

app_name = 'webapp'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('photos/create/', views.PhotoCreateView.as_view(), name='photo_create'),
    path('photos/<int:pk>/detail/', views.PhotoDetailView.as_view(), name='photo_detail'),
    path('photos/<int:pk>/update/', views.PhotoUpdateView.as_view(), name='photo_update'),
    path('photos/<int:pk>/delete/', views.PhotoDeleteView.as_view(), name='photo_delete'),
    path('photos/<int:pk>/link/create/', views.CreatePhotoToken.as_view(), name='create_token'),
    path('photos/link/<uuid:pk>/', views.RetrievePhotoToken.as_view(), name='token_photo'),
    path('albums/list/', views.AlbumListView.as_view(), name='album_list'),
    path('albums/create/', views.AlbumCreateView.as_view(), name='album_create'),
    path('albums/<int:pk>/detail/', views.AlbumDetailView.as_view(), name='album_detail'),
    path('albums/<int:pk>/update/', views.AlbumUpdateView.as_view(), name='album_update'),
    path('albums/<int:pk>/delete/', views.AlbumDeleteView.as_view(), name='album_delete'),
]

webapp/models.py
import uuid as uuid
from datetime import datetime, timedelta

from django.contrib.auth import get_user_model
from django.db import models


# Create your models here.
class Album(models.Model):
    description = models.CharField(max_length=2000, verbose_name='Название')
    title = models.CharField(max_length=50, verbose_name='Текст')
    author = models.ForeignKey(get_user_model(), verbose_name='Автор', on_delete=models.CASCADE, related_name='albums')
    created_at = models.DateTimeField(auto_now_add=True)
    is_private = models.BooleanField(default=False, blank=True, verbose_name='Приватный')

    def __str__(self):
        return self.title


class Photo(models.Model):
    image = models.FileField(verbose_name='Изображение', upload_to='images')
    description = models.CharField(max_length=50, verbose_name='Описание')
    created_at = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(get_user_model(), verbose_name='Автор', on_delete=models.CASCADE, related_name='photos')
    album = models.ForeignKey('webapp.Album', null=True, blank=True, on_delete=models.CASCADE, verbose_name='Альбом')
    is_private = models.BooleanField(default=False, blank=True, verbose_name='Приватный')

    def __str__(self):
        return self.description


class FavoritePhoto(models.Model):
    user = models.ForeignKey(get_user_model(), related_name='fav_photos', on_delete=models.CASCADE)
    photo = models.ForeignKey(Photo, related_name='fav_users', on_delete=models.CASCADE)

    class Meta:
        unique_together = ('user', 'photo')


class FavoriteAlbum(models.Model):
    user = models.ForeignKey(get_user_model(), related_name='fav_albums', on_delete=models.CASCADE)
    album = models.ForeignKey(Album, related_name='fav_users', on_delete=models.CASCADE)

    class Meta:
        unique_together = ('user', 'album')


def epire_date():
    return datetime.now() + timedelta(days=1)


class PhotoToken(models.Model):
    id = models.UUIDField(default=uuid.uuid4(), primary_key=True)
    photo = models.ForeignKey(Photo, on_delete=models.CASCADE, related_name='tokens')
    expires = models.DateTimeField(default=epire_date)

templates/album/create.html
{% extends 'base.html' %}
{% block title %}Добавить альбом{% endblock %}
{% block nav %} {% endblock %}
{% block content %}
    <h1>Добавить альбом</h1>
    <form action="{% url "webapp:album_create" %}" method="post">
        {% include 'partial/form.html' with button_text="Добавить" %}
    </form>
{% endblock %}

templates/album/delete.html
{% extends 'base.html' %}
{% block title %}Удаление Альбома{% endblock %}
{% block content %}
    <div>
        <form action="{% url 'webapp:album_delete' album.id %}" method="POST">
            {% csrf_token %}
            <div class="card text-center" style="max-width: 18rem;">
                <div class="card-header">
                </div>
                <div class="card-body">
                    <h5 class="card-title">Удаление альбома:</h5>
                    <p class="card-text">Вы действительно хотите удалить альбом? <br> {{ album.description }}</p>
                    <div class="gap-2 col-6" style="float: right">
                        <a>
                            <button class="btn btn-danger" type="submit">Да</button>
                        </a>
                        <a href="{% url "webapp:album_detail" album.id %}">
                            <button class="btn btn-primary" type="button">Нет</button>
                        </a>
                    </div>
                </div>
                <div class="card-footer">
                </div>
            </div>
        </form>
    </div>
{% endblock %}

templates/album/detail.html
{% extends 'base.html' %}
{% block title %}Главная{% endblock %}
{% block content %}
    <div>
        <br>
        <p class="font-weight-bold">Название: {{ album.title }}</p>
        <p class="font-italic">Описание: {{ album.description }}</p>

        {% if request.user.is_authenticated %}
            <button id="un-fav-btn-{{ album.id }}" class="btn btn-danger"
                    {% if album.id not in fav_albums %}hidden{% endif %}
                    onclick="unFavouriteAlbum({{ album.id }})">Удалить из избранного
            </button>
            <button id="fav-btn-{{ album.id }}" class="btn btn-success"
                    {% if album.id in fav_albums %}hidden{% endif %}
                    onclick="favouriteAlbum({{ album.id }})">
                Добавить в избранного
            </button>
        {% endif %}
    </div>
    <br>
    {% if request.user == album.author or perms.webapp.change_album %}
        <a href="{% url 'webapp:album_update' album.id %}" class="btn btn-primary">Редактировать</a>
    {% endif %}
    {% if request.user == album.author or perms.webapp.delete_album %}
        <a href="{% url 'webapp:album_delete' album.id %}" class="btn btn-danger">Удалить</a>
    {% endif %}

    <br>
    <br>
    <h3>Фото</h3>
    <div class="row">
        {% for p in album.photo_set.all %}
            {% if not p.is_private or p.author == request.user %}
                <div class="col-md-3">
                    <img src="{{ p.image.url }}" style=" width: 10rem; height:
                10rem; background-repeat: no-repeat;" alt="">
                    <br>
                    <a href="{% url 'webapp:photo_detail' p.id %}" style="text-decoration: none; "
                       class="text-warning">{{ p.description }}</a>
                </div>
            {% endif %}
        {% endfor %}
    </div>
    <br>
    <div>
        <h3>В Избранном у пользователей:</h3>
        {% for fav_user in album.fav_users.all %}
            <p><a href="{% url 'accounts:user_profile' fav_user.user.id %}">{{ fav_user.user.username }}</a></p>
        {% endfor %}
        <br>
        <br>
    </div>
{% endblock %}

{% block scripts %}
    <script>
        function unFavouriteAlbum(id) {
            fetch('/api/album/unfavorite/' + id)
                .then(function (response) {
                    return response.json();
                })
                .then(function (response) {
                    if (response.success) {
                        document.getElementById("fav-btn-" + id).hidden = false;
                        document.getElementById("un-fav-btn-" + id).hidden = true;
                    } else {
                        console.log(response);
                    }
                });
        }

        function favouriteAlbum(id) {
            fetch('/api/album/favorite/' + id)
                .then(function (response) {
                    return response.json();
                })
                .then(function (response) {
                    if (response.success) {
                        document.getElementById("un-fav-btn-" + id).hidden = false;
                        document.getElementById("fav-btn-" + id).hidden = true;
                    } else {
                        console.log(response);
                    }
                });
        }
    </script>
{% endblock %}

templates/album/list.html
{% extends 'base.html' %}
{% block title %}Главная{% endblock %}
{% block content %}
    <br>
    <div class="row">
        {% for a in albums %}
            <div class="card m-2 bg-light" style="width: 16rem;">
                <a href="{% url 'webapp:album_detail' a.pk %}" style="text-decoration: none">
                    <div class="card-body">
                        <h5 class="card-title">Альбом {{ a.id }}</h5>
                        <h6 class="card-subtitle mb-2 text-muted">Название:{{ a.title }}</h6>
                        <p class="card-text">Описание: {{ a.description }} </p>
                        <p class="card-text">Автор:{{ a.author }} </p>

                    </div>
                </a>
            {% if request.user.is_authenticated %}
                <button id="un-fav-btn-{{ a.id }}" class="btn btn-danger"
                        {% if a.id not in fav_albums %}hidden{% endif %}
                        onclick="unFavouriteAlbum({{ a.id }})">Удалить из избранного
                </button>
                <button id="fav-btn-{{ a.id }}" class="btn btn-success"
                        {% if a.id in fav_albums %}hidden{% endif %}
                        onclick="favouriteAlbum({{ a.id }})">
                    Добавить в избранного
                </button>
            {% endif %}
            </div>

        {% endfor %}
    </div>
{% endblock %}
{% block scripts %}
    <script>
        function unFavouriteAlbum(id) {
            fetch('/api/album/unfavorite/' + id)
                .then(function (response) {
                    return response.json();
                })
                .then(function (response) {
                    if (response.success) {
                        document.getElementById("fav-btn-" + id).hidden = false;
                        document.getElementById("un-fav-btn-" + id).hidden = true;
                    } else { console.log(response);}
                });
        }

        function favouriteAlbum(id) {
            fetch('/api/album/favorite/' + id)
                .then(function (response) {
                    return response.json();
                })
                .then(function (response) {
                    if (response.success) {
                        document.getElementById("un-fav-btn-" + id).hidden = false;
                        document.getElementById("fav-btn-" + id).hidden = true;
                    } else { console.log(response);}
                });
        }
    </script>
{% endblock %}

templates/album/update.html
{% extends 'base.html' %}
{% block title %}Редактировать альбом{% endblock %}
{% block nav %} {% endblock %}
{% block content %}
    <h1>Редактировать альбом</h1>
        <form action="{% url "webapp:album_update" album.id %}" method="post" >
        {% include 'partial/form.html' with button_text="Сохранить" %}
    </form>
    <br>
    <p><a href="{% url "webapp:album_detail" album.pk %}" class="btn btn-success" style="float: left">Назад</a></p>
{% endblock %}