accounts/urls.py
from django.urls import path, include

from accounts.views import ProfileView

app_name = 'accounts'


urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('profile/<int:pk>', ProfileView.as_view(), name='user_profile')
]

api/urls.py
from django.urls import path
from . import views

app_name = 'api'

urlpatterns = [
    path('photo/favorite/<int:pk>/', views.FavoritePhotoApiView.as_view(), name='fav_photo'),
    path('photo/unfavorite/<int:pk>/', views.UnFavoritePhotoApiView.as_view(), name='unfav_photo'),
    path('album/favorite/<int:pk>/', views.FavoriteAlbumView.as_view(), name='fav_photo'),
    path('album/unfavorite/<int:pk>/', views.UnFavoriteAlbumApiView.as_view(), name='unfav_photo'),
]

exam9/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('auth/', include('accounts.urls')),
    path('api/', include('api.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webapp/urls.py
from django.urls import path
from . import views

app_name = 'webapp'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('photos/create/', views.PhotoCreateView.as_view(), name='photo_create'),
    path('photos/<int:pk>/detail/', views.PhotoDetailView.as_view(), name='photo_detail'),
    path('photos/<int:pk>/update/', views.PhotoUpdateView.as_view(), name='photo_update'),
    path('photos/<int:pk>/delete/', views.PhotoDeleteView.as_view(), name='photo_delete'),
    path('photos/<int:pk>/link/create/', views.CreatePhotoToken.as_view(), name='create_token'),
    path('photos/link/<uuid:pk>/', views.RetrievePhotoToken.as_view(), name='token_photo'),
    path('albums/list/', views.AlbumListView.as_view(), name='album_list'),
    path('albums/create/', views.AlbumCreateView.as_view(), name='album_create'),
    path('albums/<int:pk>/detail/', views.AlbumDetailView.as_view(), name='album_detail'),
    path('albums/<int:pk>/update/', views.AlbumUpdateView.as_view(), name='album_update'),
    path('albums/<int:pk>/delete/', views.AlbumDeleteView.as_view(), name='album_delete'),
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <title>{% block title %}Photo album{% endblock %}</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
</head>

<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">

        <a class="navbar-brand" href={% url 'webapp:index' %}>Домой</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                {% block nav %}{% endblock %}
                <li class="nav-item">
                    <a href="{% url 'webapp:photo_create' %}" class="nav-link">Создать Фото</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'webapp:album_create' %}" class="nav-link">Создать Альбом</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'webapp:album_list' %}" class="nav-link">Посмотреть Альбом</a>
                </li>
                {% if not user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:login' %}?next={{ request.get_full_path }}">Вход</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link"
                           href="{% url 'accounts:user_profile' request.user.pk %}">Профиль</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link"
                           href="{% url 'accounts:logout' %}?next={{ request.get_full_path }}">Выход</a>
                    </li>
                {% endif %}

            </ul>
        </div>

    </div>
</nav>

<div id="content" class="container">
    {% block content %}{% endblock %}
</div>
{% block scripts %}{% endblock %}
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block title %}Главная{% endblock %}
{% block content %}
    <br>
    <div class="row">
        <br>
        {% for p in photos %}
            <div class="col-md-3">
                <br>
                <a href="{% url 'webapp:photo_detail' p.id %}"><img src="{{ p.image.url }}" style=" width: 10rem; height:
                10rem; background-repeat: no-repeat; cursor: pointer" alt=""></a>
                <br>
                <a href="{% url 'webapp:photo_detail' p.id %}">{{ p.description }}</a>
                <br>
                {% if request.user.is_authenticated %}
                    <button id="un-fav-btn-{{ p.id }}" class="btn btn-danger"
                            {% if p.id not in fav_photos %}hidden{% endif %}
                            onclick="unFavouritePhoto({{ p.id }})">Удалить из избранного
                    </button>
                    <button id="fav-btn-{{ p.id }}" class="btn btn-success"
                            {% if p.id in fav_photos %}hidden{% endif %}
                            onclick="favouritePhoto({{ p.id }})">
                        Добавить в избранного
                    </button>
                {% endif %}
            </div>

        {% endfor %}
    </div>
{% endblock %}

{% block scripts %}
    <script>
        function unFavouritePhoto(id) {
            fetch('/api/photo/unfavorite/' + id)
                .then(function (response) {
                    return response.json();
                })
                .then(function (response) {
                    if (response.success) {
                        document.getElementById("fav-btn-" + id).hidden = false;
                        document.getElementById("un-fav-btn-" + id).hidden = true;
                    } else { console.log(response);}
                });
        }

        function favouritePhoto(id) {
            fetch('/api/photo/favorite/' + id)
                .then(function (response) {
                    return response.json();
                })
                .then(function (response) {
                    if (response.success) {
                        document.getElementById("un-fav-btn-" + id).hidden = false;
                        document.getElementById("fav-btn-" + id).hidden = true;
                    } else { console.log(response);}
                });
        }
    </script>
{% endblock %}